Feature/creation batiments
ProgHunter/Seigneurie pull request #13
Opened 2023-03-29 02:49 UTC by ProgHunter

- Création d'un "Lot de ressource" pour exprimer le coût des bâtiment.
- Corrections mineur au module de ressource, une plus grande refonte sera fait ultérieurement.
- Création du gestionnaire de bâtiments et des tests associés.

2023-03-29 02:52 UTC, ProgHunter commented on Assets/Scripts/Ressources/AbstractRessource.cs
> +    public struct LotRessources
Une classe sera créée dans un autre fichier pour remplacer cette struct bientôt (en même temps qu'une refonte partielle du module de ressources)

2023-04-01 15:31 UTC, Popcorns26 requested changes
Deux petits renomages

2023-04-01 15:31 UTC, Popcorns26 commented on Assets/Scripts/Batiments/GestionnaireBatiments.cs
> +        /// <see cref="BatimentEnum"/> constitu le batiment en contruction
Constitue le bâtiment

2023-04-01 15:31 UTC, Popcorns26 commented on Assets/Scripts/Batiments/GestionnaireBatiments.cs
> +            batimentConfigDic = new Dictionary<BatimentEnum, AbstraitBatimentConfig>
Tu peux renommer ca batimentConfigDict? J'aime pas lire dic

2023-04-02 02:30 UTC, merged