Feature/Prérequis pour les batiments et les ressources (verrouillé)
ProgHunter/Seigneurie pull request #17
Opened 2024-09-02 03:15 UTC by ProgHunter

- Ajout de la notion de prérequis pour les bâtiments. Un bâtiment est verrouillé si on n'a pas les prérequis.
- Ajout de la notion de prérequis pour les ressources. Une ressource est verrouillée si on n'a pas les prérequis.
- Modification des configs de ressource pour utiliser la classe Qte.
- Correction des noms des membres des classes qui commencent avec des minuscules.
- Autres petits fix mineurs.

2024-09-07 22:04 UTC, Popcorns26 requested changes

2024-09-07 22:04 UTC, Popcorns26 commented on Assets/Scripts/Batiments/HotelDeVilleConfig.cs
> +using JetBrains.Annotations;
Est-ce que c'est using sont utiles?

2024-09-07 22:04 UTC, Popcorns26 commented on Assets/Scripts/Batiments/LotBatiments.cs
> +        public Dictionary<BatimentEnum, Qte> BatimentsDic;
Tu peux appeler ça BatimenDict plz?

2024-09-07 22:04 UTC, Popcorns26 commented on Assets/Scripts/Ressources/AbstraitRessourceConfig.cs
> +using Utils;
Usings?

2024-09-07 22:04 UTC, Popcorns26 commented on Assets/Scripts/Ressources/BoisConfig.cs
> +using Utils;
Check usings

2024-09-08 16:41 UTC, ProgHunter commented on Assets/Scripts/Batiments/HotelDeVilleConfig.cs
> +using JetBrains.Annotations;
nop

2024-09-08 16:42 UTC, ProgHunter commented on Assets/Scripts/Ressources/AbstraitRessourceConfig.cs
> +using Utils;
Sont ok, UnityEngine pour le sprite, Batiment pour le prérequis, Utils pour la Qte.

2024-09-08 16:43 UTC, ProgHunter commented on Assets/Scripts/Ressources/BoisConfig.cs
> +using Utils;
Ok aussi

2024-09-08 17:21 UTC, Popcorns26 approved these changes

2024-09-08 17:22 UTC, merged