Main UI  premier brouillon
ProgHunter/Seigneurie pull request #20
Opened 2024-09-08 20:11 UTC by Popcorns26

Main UI contient :

- Infos du joueur
- Quantités de ressources
- Gestion professions
- Début d'affichage des productions
- Début des bâtiments

2024-09-09 03:44 UTC, ProgHunter commented on Assets/ThirdPartyAssets/TextMesh Pro/Sprites/EmojiOne.png
:)

2024-09-09 03:45 UTC, ProgHunter commented on Assets/ThirdPartyAssets/TextMesh Pro/Resources/LineBreaking Leading Characters.txt
yes

2024-09-09 03:46 UTC, ProgHunter commented on Assets/ThirdPartyAssets/TextMesh Pro/Resources/LineBreaking Following Characters.txt
hmm

2024-09-09 03:47 UTC, ProgHunter commented on Assets/ThirdPartyAssets/TextMesh Pro/Documentation/TextMesh Pro User Guide 2016.pdf
oky

2024-09-09 04:18 UTC, ProgHunter requested changes

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/Productions/AbstraitProduction.cs
> -        /// <see cref="EfficacitePourcent"/>
Garder la majuscule pour aller avec l'accesseur/mutateur ?

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/Productions/Tickeur.cs
> +        // Tick � chaque 2 secondes
Ligne de commentaire dédoublée.

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/UI/AssignationProfessionsUI.cs
> +        public void InitProfession(ProfessionEnum value, Action pourcentageTotal)
value?

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/UI/AssignationProfessionsUI.cs
> +            if (_pourcentageActuel > 99)
const int pcMax = 100;
if (_pourcentageActuel >= pcMax)
return;
...

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/UI/AssignationProfessionsUI.cs
> +        private void OnSliderValueChanged(float value)
value -> [0,1], ou [0, 100] ?

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/UI/IndicateurRessource.cs
> +                _ressourceRepresentee = value;
value c'est un peu générique..

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/UI/MainUI.cs
> +        [SerializeField] private VueGestionnaireProductions _vueGestionnaireProductions;
nice, j'aime bien qu'on sépare les différentes vues ainsi. 👍

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/UI/VueGestionnaireProfessions.cs
> +        public void UpdatePourcentage()
UpdatePourcentageRestant

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/UI/VueProductionRessource.cs
> +            //_production.text = GestionnaireProductions.Instance.;
wip, on pourra se faire une session de peer programming pour ajouter ce bout-là.

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Scripts/Utils/EnumUtils.cs
> +using System;
System est pas en trop ?

2024-09-09 04:18 UTC, ProgHunter commented on Assets/Tests/Ressources/TestsInventaireRessources.cs
> -        public void TestTransactionLotRessourcesBloquantRefuse()
Laissé sans accent, ça fait bizarre sinon.

2024-09-12 00:59 UTC, Popcorns26 commented on Assets/Scripts/UI/AssignationProfessionsUI.cs
> +        private void OnSliderValueChanged(float value)
C'est 0 à 100. C'est défini dans le component

2024-09-12 01:01 UTC, Popcorns26 commented on Assets/Scripts/Utils/EnumUtils.cs
> +using System;
Non c'est utilisé

2024-09-12 01:03 UTC, Popcorns26 commented on Assets/Tests/Ressources/TestsInventaireRessources.cs
> -        public void TestTransactionLotRessourcesBloquantRefuse()
C'est juste sur github je crois.
![image](https://github.com/user-attachments/assets/8a8221d7-53bf-41f4-a04f-4d53dc83da1e)

2024-09-12 01:04 UTC, Popcorns26 commented on Assets/Scripts/UI/VueGestionnaireProfessions.cs
> +        public void UpdatePourcentage()
Done

2024-09-12 01:05 UTC, Popcorns26 commented on Assets/Scripts/UI/AssignationProfessionsUI.cs
> +            if (_pourcentageActuel > 99)
Done

2024-09-12 01:06 UTC, Popcorns26 commented on Assets/Scripts/UI/AssignationProfessionsUI.cs
> +        public void InitProfession(ProfessionEnum value, Action pourcentageTotal)
Changé pour profession

2024-09-12 01:06 UTC, Popcorns26 commented on Assets/Scripts/Productions/Tickeur.cs
> +        // Tick � chaque 2 secondes
Done

2024-09-12 01:07 UTC, Popcorns26 commented on Assets/Scripts/Productions/AbstraitProduction.cs
> -        /// <see cref="EfficacitePourcent"/>
Ok

2024-09-12 02:31 UTC, ProgHunter requested changes

2024-09-12 02:31 UTC, ProgHunter commented on Assets/Scripts/UI/AssignationProfessionsUI.cs
> +            if (_pourcentageActuel <= 0)
private const int _pcMin = 0;

2024-09-12 02:40 UTC, Popcorns26 commented on Assets/Scripts/UI/AssignationProfessionsUI.cs
> +            if (_pourcentageActuel <= 0)
Done

2024-09-12 02:41 UTC, ProgHunter approved these changes
noice!

2024-09-12 02:43 UTC, merged